server:
  port: 8084
spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb+srv://Chanul:Chanul%40123@cluster0.a9iq4f8.mongodb.net/payment_db?appName=Cluster0
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
