server:
  port: 8081
spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb+srv://shehanmadhuwantha343_db_user:toPWGhVSAPPtnmTh@cluster0.ajij2pj.mongodb.net/account_db?appName=Cluster0
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000
