server:
  port: 8083
spring:
  application:
    name: ride-service
  data:
    mongodb:
      uri: mongodb+srv://pasinduchamikaragunasekara_db_user:6heYJj5NRxjip5YZ@cluster0.dhbsycl.mongodb.net/ride_db?appName=Cluster0&tls=true&tlsAllowInvalidCertificates=true
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
