server:
  port: 8083
spring:
  application:
    name: ride-service
  data:
    mongodb:
      uri: mongodb+srv://udithaasiri35_db_user:Asiri%40123@cluster0.jomudrq.mongodb.net/ride_db?appName=Cluster0&tls=true&tlsAllowInvalidCertificates=true
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
